server:
  port: 0

spring:
  main:
    banner-mode: off
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
      jdbc.time_zone: UTC
  sql:
    init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/commerce
    schema: warehouse
    username: user
    password: 12345